<h1> Introdução ao Python </h1>

O Python é uma linguagem de programação de alto nível, interpretada e de propósito geral. É uma linguagem bastante utilizada em áreas como a ciência de dados, aprendizado de máquina, processamento de sinais e sistemas, entre outras. A linguagem possui uma sintaxe simples e fácil de aprender, além de uma vasta biblioteca padrão e de terceiros, tornando-a bastante versátil.

<h2> 1. Apresentar Resultados na Tela </h2>

Para apresentar resultados na tela, utilizamos a função `print()`. Por exemplo, para imprimir a string "Olá, mundo!", basta executar o seguinte comando:

In [1]:
print("Olá, mundo!")

Olá, mundo!


<h2> 2. Operações com Números Reais </h2>

Para fazer operações com números reais, utilizamos os operadores aritméticos padrão (`+`, `-`, `*`, `/`). Por exemplo, para calcular a soma, subtração, multiplicação e divisão de dois números reais, basta executar o seguinte código:

In [1]:
a = 2.5
b = 3.7

c = a + b
d = a - b
e = a*b
f = a/b

print("a + b = ", c)
print("a - b = ", d)
print("a * b = ", e)
print("a / b = ", f)

a + b =  6.2
a - b =  -1.2000000000000002
a * b =  9.25
a / b =  0.6756756756756757


<h2> 3. Estruturas Condicionais </h2>

As estruturas condicionais permitem executar um bloco de código somente se uma condição for atendida. A estrutura condicional básica do Python é o `if`. Por exemplo, para verificar se um número é positivo, basta executar o seguinte código:

In [2]:
x = 5
if x > 0:
    print("x é positivo")

x é positivo


Também é possível utilizar a estrutura condicional `else` para executar um bloco de código caso a condição do `if` não seja atendida. Por exemplo:

In [3]:
x = -2
if x > 0:
    print("x é positivo")
else:
    print("x é negativo ou zero")

x é negativo ou zero


O comando `elif` é utilizado para definir uma condição alternativa. Por exemplo, para verificar se um número é positivo, negativo ou zero, basta executar o seguinte código:

In [4]:
x = 0
if x > 0:
    print("x é positivo")
elif x < 0:
    print("x é negativo")
else:
    print("x é zero")

x é zero


<h2> 4. Laços e Estruturas de Repetição </h2>

Os laços permitem executar um bloco de código várias vezes. O laço básico do Python é o `for`. Por exemplo, para imprimir os números de 0 a 4 na tela, basta executar o seguinte código:

In [5]:
for i in range(5):
    print(i)

0
1
2
3
4


Nesse exemplo, o comando `range(5)` cria uma sequência de números de 0 a 4. O laço for percorre essa sequência e a variável `i` assume cada um dos valores. O comando `print(i)` exibe o valor de `i` na tela. Também é possível utilizar o laço `while` para executar um bloco de código enquanto uma condição for verdadeira. Por exemplo, para imprimir os números de 0 a 4 na tela utilizando o laço `while`, basta executar o seguinte código:

In [6]:
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


<h2> 5. Funções </h2>

As funções são blocos de código que executam uma tarefa específica e podem ser chamados em outros lugares do programa. Elas permitem que o código seja organizado em módulos lógicos e reutilizáveis.

Para criar uma função, usamos a palavra reservada `def`, seguida pelo nome da função, uma lista de parâmetros (se houver) entre parênteses e dois pontos. O bloco de código identado abaixo é executado sempre que a função é chamada.

Por exemplo, para criar uma função que calcula a soma de dois números, podemos usar o seguinte código:

In [7]:
def soma(a, b):
    resultado = a + b
    print("A soma é:", resultado)

Para chamar uma função, basta digitar o nome da função, seguido por uma lista de argumentos (se houver) entre parênteses. Por exemplo, para chamar a função `soma` e calcular a soma dos números 2 e 3, basta executar o seguinte código:

In [8]:
soma(2, 3)

A soma é: 5


O comando `return` é utilizado para retornar um valor calculado dentro da função. Por exemplo, para criar uma função que retorna a soma de dois números, podemos usar o seguinte código:

In [9]:
def soma(a, b):
    resultado = a + b
    return resultado

Para chamar a função e armazenar o resultado da soma em uma variável, basta executar o seguinte código:

In [10]:
x = soma(2, 7)
print("A soma é:", x)

A soma é: 9


<h2> 6. Vetores e Matrizes </h2>

Podemos criar vetores e matrizes de diferentes formas no Python, mas neste curso usaremos a bibliotecada `numpy`. A `numpy` é uma biblioteca para Python que permite trabalhar com vetores e matrizes de forma mais eficiente do que com a classe `list` padrão. 

Um vetor é uma sequência de valores. Em NumPy, podemos criar um vetor usando a função `array`. Por exemplo, para criar um vetor que contém os números 1, 2 e 3, podemos usar o seguinte código:

In [11]:
import numpy as np

v = np.array([1, 2, 3])
print(v)

[1 2 3]


Com a função `arange()` é possível gerar um vetor com valores espaçados de acordo com um intervalo e um passo definidos pelo usuário. A sintaxe é a seguinte:

```python
np.arange(start, stop, step)
```

onde:

<ul>
<li>`start`: o valor inicial do intervalo (inclusive);</li>
<li>`stop`: o valor final do intervalo (exclusive);</li>
<li>`step`: o espaçamento entre os valores.</li>
</ul>

In [12]:
import numpy as np

x1 = np.arange(0,12,2)
print(x1)

x2 = np.arange(0,3,0.5)
print(x2)

x3 = np.arange(3,0,-0.4)
print(x3)

x4 = np.arange(0,10)
print(x4)

[ 0  2  4  6  8 10]
[0.  0.5 1.  1.5 2.  2.5]
[3.  2.6 2.2 1.8 1.4 1.  0.6 0.2]
[0 1 2 3 4 5 6 7 8 9]


O primeiro vetor, `x1`, é composto por elementos que iniciam no 0, terminam no 12 (mas não incluído esse), com passo de 2. O segundo vetor, `x2`, é composto por elementos que iniciam no 0, terminam no 3 (mas não incluído esse), com passo de 0,5. O terceiro vetor, `x3`, é composto por elementos que iniciam no 3, terminam no 0 (mas não incluído esse), com passo de -0,4. Nesse caso, teremos um vetor que os elementos diminuem de valor. Quando o passo é igual a 1, esse pode ser omitido. Foi o que aconteceu no vetor `x4`.

Para acessar os elementos de um vetor, fazemos da mesma forma do C. Todavia, o Python permite algumas facilidades, como acessar o último elemento do vetor, usando o índice `-1` e acessar um sub-vetor dentro de um vetor maior, usando o slicing. A sintaxe básica de slicing é `start:stop:step`, onde `start` é o índice de início, `stop` é o índice de fim e `step` é o tamanho do passo. Por exemplo, vamos criar um vetor e realizar diferentes acessos à ele:

In [13]:
import numpy as np

x1 = np.arange(0,12,2)
print(x1[0])
print(x1[3])
print(x1[-1])
print(x1[0:6:2])

0
6
10
[0 4 8]


Podemos acessar os elementos do vetor usando o índice. Por exemplo, para acessar o primeiro elemento do vetor, podemos usar o seguinte código:

In [14]:
x1[3] = -8
print(x1)

[ 0  2  4 -8  8 10]


A função `linspace` da biblioteca `numPy` é utilizada para criar uma sequência de valores igualmente espaçados dentro de um intervalo especificado. Isso é particularmente útil ao gerar valores para plotagem de gráficos, realizar interpolações ou qualquer outra situação onde seja necessário um conjunto uniformemente espaçado de valores.

In [1]:
import numpy as np

start = 0       # Valor inicial da sequência
end = 10        # Valor final da sequência
num_points = 50 # Número de pontos desejados na sequência

# Usando linspace para gerar a sequência de valores
x = np.linspace(start, end, num_points)
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

Uma matriz é uma tabela de valores. Com a `numpy`, podemos representar uma matriz usando um array multidimensional. Cada dimensão representa uma linha ou uma coluna da matriz. Por exemplo, para criar uma matriz 2x2, podemos usar o seguinte código:

In [15]:
import numpy as np

m = np.array([[1, 2], [3, 4]])
print(m)

[[1 2]
 [3 4]]


Podemos acessar um elemento da matriz usando dois índices: o primeiro para a linha e o segundo para a coluna. Por exemplo, para acessar o elemento na segunda linha e primeira coluna da matriz `m`, podemos usar o seguinte código:

In [16]:
segunda_linha_primeira_coluna = m[1][0]
print(segunda_linha_primeira_coluna)

3


Podemos alterar um elemento da matriz atribuindo um novo valor aos seus índices. Por exemplo, para alterar o elemento na segunda linha e primeira coluna da matriz `m` para o valor 5, podemos usar o seguinte código:

In [17]:
m[1][0] = 5
print(m)

[[1 2]
 [5 4]]


Para somar dois vetores em Python, podemos usar o seguinte código:

In [18]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b

print(c)

[5 7 9]


Para calcular o produto ponto-a-ponto (também conhecido como produto elemento-a-elemento) de dois vetores em Python, podemos usar o seguinte código:

In [19]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a * b

print(c)

[ 4 10 18]


Multiplicar um vetor ou matriz por um escalar significa multiplicar cada elemento do vetor ou matriz pelo escalar. Em NumPy, podemos multiplicar um vetor ou matriz por um escalar usando a multiplicação usual `*`, por exemplo:

In [20]:
import numpy as np

a = np.array([1, 2, 3])

b = a * 2

print(b)

[2 4 6]


Para somar duas matrizes em Python, podemos usar o seguinte código:

In [21]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = a + b

print(c)

[[ 6  8]
 [10 12]]


Para calcular o produto de duas matrizes em Python, podemos usar o seguinte código:

In [22]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.dot(a, b)

print(c)

[[19 22]
 [43 50]]


Além das operações básicas que foram apresentadas no tutorial anterior, existem diversas outras operações que podemos realizar com vetores e matrizes em Python usando a biblioteca NumPy.

<h2> 7. Números Complexos </h2>

O Python pode ser utilizado como uma calculadora para números complexos. Para gerar um número complexo em Python, podemos utilizar a notação retangular, tal como:

$$
z = a + jb
$$

Com isso, podemos  calcular a parte real (`np.real()`), parte imaginária (`np.imag()`), magnitude (`np.abs()`) e fase (`np.angle()`) de um número complexo. 

Além disso, a biblioteca `numpy` permite o acesso à várias ferramentas matemáticas, como função cosseno (`numpy.cos()`), função seno (`numpy.sin()`) ou o número $\pi$ (`numpy.pi`).

Vamos calcular a parte real, imaginária, módulo e fase do número complexo $z = 3 + j4$.

In [23]:
import numpy as np

z = 3 + 1j*4;
print('Real = ',np.real(z))
print('Imaginário = ',np.imag(z))
print('Módulo = ',np.abs(z))
print('Fase (rad) = ',np.angle(z))
print('Fase (graus) = ',np.abs(z)*180/np.pi)

Real =  3.0
Imaginário =  4.0
Módulo =  5.0
Fase (rad) =  0.9272952180016122
Fase (graus) =  286.4788975654116


Da mesma forma, podemos gerar um número complexo utilizando a notação polar:

$$
z = re^{j\theta}
$$

Para isso, vamos utilizar a função `np.exp()` da biblioteca `numpy`. 

Vamos calcular a parte real, imaginária, módulo e fase do número complexo $z = 2e^{\pi/3}$.

In [25]:
z = 2*np.exp(1j*np.pi/3)

print('Real = ',np.real(z))
print('Imaginário = ',np.imag(z))
print('Módulo = ',np.abs(z))
print('Fase (rad) = ',np.angle(z))
print('Fase (graus) = ',np.abs(z)*180/np.pi)

Real =  1.0000000000000002
Imaginário =  1.7320508075688772
Módulo =  2.0
Fase (rad) =  1.0471975511965976
Fase (graus) =  114.59155902616465


A operação de complexo conjungado pode ser realizada através da função `np.conj()`

Sendo $z = 3 + j4$, determine o complexo conjugado de $z$.

In [26]:
z = 3 + 1j*4

zconj = np.conj(z)
print('z* = ',zconj)

z* =  (3-4j)


Obviamente, podemos realizar operações de soma, subtração, multiplicação e divisão com números complexos em Python. Para isso utilizaremos os operadores de soma, subtração, multiplicação e divisão convencionais, assim como em outras linguagens de programação.

Então dado os números complexos $z_1 = 3 + j4$ e $z_2 = 5 - j2$, vamos determinar $z_1 + z_2$, $z_1 - z_2$, $z_1z_2$ e $z_1/z_2$.

In [27]:
import numpy as np

z1 = 3 + 1j*4;
z2 = 5 - 1j*2;

zsoma = z1 + z2;
zsub = z1 - z2;
zmul = z1*z2;
zdiv = z1/z2;
print('z1 + z2 = ',zsoma);
print('z1 - z2 = ',zsub);
print('z1*z2 = ',zmul);
print('z1/z2 = ',zdiv);

z1 + z2 =  (8+2j)
z1 - z2 =  (-2+6j)
z1*z2 =  (23+14j)
z1/z2 =  (0.24137931034482757+0.896551724137931j)


Terminamos nossa primeira aula por aqui. Com esses conceitos, creio que você não terá dificuldade nenhuma em entender como o Python pode ser utilizado para a análise de Sinais e Sistemas Lineares.